-- Quick setup script to create admin user
-- Run this in PostgreSQL to quickly create the test user

-- Create admin user with hashed password for '123456'
-- The hash is: $2a$10$YourActualHashHere (will be generated by script)

INSERT INTO "Usuario" (username, password, "createdAt")
VALUES ('admin@test.com', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGa.29WozorflFJjO6', NOW())
ON CONFLICT (username) DO NOTHING;

-- Verify the user was created
SELECT id, username, "createdAt" FROM "Usuario" WHERE username = 'admin@test.com';
